### ISSUE TITLE
[버튼] Hydration Failed Error

### ISSUE THREAD

**Issue by Eugene-A-01** [like-tenten/tenten#43]
## Error / Bug

<img width="951" alt="image" src="https://github.com/like-tenten/tenten/assets/70089733/c2cd7e14-3126-4c89-aec5-d81f54ba200e">

## 솔루션

(해결한 경우, 솔루션을 적어주세요.)

**Comment by naya-h2** [comment]
`<button>` 태그를 다시 `<button> `태그로 감싸서 일어난 에러였습니다! 해결!
