### ISSUE TITLE
[/myboard] api 요청 로딩 시 UI 문제

### ISSUE THREAD

**Issue by naya-h2** [like-tenten/tenten#45]
## Error / Bug
- 새로운 대시보드 생성 시 로직은 `api 요청 -> 데이터 생성 완료 후 id 받아와야함 -> /board/{id} 페이지로 연결` 입니다.
- 해당 id 페이지로 이동하기 위해서 무조건 데이터 생성 완료 후까지 기다려야 하기에 await을 사용하였습니다.
- 그런데 api 요청이 완료되기까지의 시간이 생각보다 길어서 **사용자 입장에서 내 요청이 들어간건지, 들어가지 않은 건지 알 수 없어 충분히 반복적인 요청을 보낼 여지가 있어 보입니다!**
- 이 문제를 어떻게 해결할 수 있을까요??
- api 요청을 보내고, 생성 버튼을 inactive로 막는게 최선의 방법일지 잘.. 모르겠습니다~!
- 도와주세용 !!

## 스크린샷
![api로딩너무길다](https://github.com/like-tenten/tenten/assets/103186362/ca51ac55-65a7-48aa-9331-f2a79b2635ea)

## 솔루션

(해결한 경우, 솔루션을 적어주세요.)

**Comment by Ssong-Q** [comment]
https://mycodings.fly.dev/blog/2023-09-17-how-to-use-react-query-and-usequery
https://mycodings.fly.dev/blog/2022-08-29-react-lazy-react-suspense-guide

react query의 isLoading이나 react suspense를 이용해볼까욥
